const eventAreasData = {
	en: {
		eventName: "Event name",
		timeStart: "Time start",
		timeEnd: "Time end",
		description: "Description",
		titleName: "All events",
		options: "Options",
		delete: "Delete",
		edit: "Edit",
		price: "Price",
		editTitle: "Update event-area",
		eventAreas: "Event areas",
		coordX: "Coord X",
		coordY: "Coord Y",
		eventSeats: "Event seats",
		eventSeatsMap: "Event seats map",
		deleted: "(Deleted)",
		areYouSure: "Are you sure?",
		success: "Success!",
		fail: "Fail...",
	},
	ru: {
		eventName: "Название события",
		timeStart: "Дата начала",
		timeEnd: "Дата окончания",
		description: "Описание",
		titleName: "Все события",
		options: "Опции",
		delete: "Удалить",
		edit: "Изменить",
		price: "Цена",
		editTitle: "Изменение зоны",
		eventAreas: "Зоны события",
		coordX: "Координата X",
		coordY: "Координата Y",
		eventSeats: "Места",
		eventSeatsMap: "Карта мест зоны",
		deleted: "(Удалено)",
		areYouSure: "Вы уверены?",
		success: "Успешно!",
		fail: "Неудачно...",
	},
	be: {
		eventName: "Назва падзеі",
		timeStart: "Дата пачатку",
		timeEnd: "Дата заканчення",
		description: "Апісанне",
		titleName: "Усе падзеі",
		options: "Опцыі",
		delete: "Выдаліць",
		edit: "Змяніць",
		price: "Цана",
		editTitle: "Змена зоны",
		eventAreas: "Зоны падзеі",
		coordX: "Кардыната X",
		coordY: "Кардыната Y",
		eventSeats: "Месцы",
		eventSeatsMap: "Карта месцаў зоны",
		deleted: "(Выдалена)",
		areYouSure: "Вы ўпэўнены?",
		success: "Паспяхова!",
		fail: "Няўдала...",
	}
}

export default eventAreasData;