const eventListData = {
	en: {
		venueName: "Venue name",
		create: "Create",
		createEvent: "Create event",
		timeStart: "Time start",
		timeEnd: "Time end",
		description: "Description",
		details: "Details",
		name: "Name",
		titleName: "All events",
		image: "Image",
		options: "Options",
		delete: "Delete",
		edit: "Edit",
		layoutName: "Layout name",
		price: "Price",
		imageUrl: "URL image",
		editTitle: "Update event",
		createTitle: "Create event",
		failDate: "Fail. This date is busy or incorrect for specified venue.",
		success: "Success!",
		areYouSure: "Are you sure?",
		fail: "Fail...",
	},
	ru: {
		venueName: "Место проведения",
		create: "Создать",
		createEvent: "Создать событие",
		timeStart: "Дата начала",
		timeEnd: "Дата окончания",
		description: "Описание",
		details: "Детали",
		name: "Название",
		titleName: "Все события",
		image: "Изображение",
		options: "Опции",
		delete: "Удалить",
		edit: "Изменить",
		layoutName: "Название макета",
		price: "Цена",
		imageUrl: "URL изображения",
		editTitle: "Изменение события",
		createTitle: "Создание события",
		failDate: "Ошибка. Указанная дата занята или неккоректна для данного места проведения.",
		success: "Успешно!",
		areYouSure: "Вы уверены?",
		fail: "Неудачно...",
	},
	be: {
		venueName: "Месца правядзення",
		create: "Стварыць",
		createEvent: "Стварыць падзею",
		timeStart: "Дата пачатку",
		timeEnd: "Дата заканчення",
		description : "Апісанне",
		details: "Дэталі",
		name: "Назва",
		titleName: "Усе падзеі",
		image: "Малюнак",
		options: "Опцыі",
		delete: "Выдаліць",
		edit: "Змяніць",
		layoutName: "Назва макета",
		price: "Цана",
		imageUrl: "URL малюнка",
		editTitle: "Змена падзеі",
		createTitle: "Стварэнне падзеі",
		failDate: "Памылка. Указаная дата занятая або некарэктная для дадзенага месца правядзення.",
		success: "Паспяхова!",
		areYouSure: "Вы ўпэўнены?",
		fail: "Няўдала...",
	}
}

export default eventListData;