const userData = {
    en: {
        age: "Age",
        boughtTickets: "Bougth tickets",
        email: "Email",
        eventManagement: "Events management",
        exit: "Exit",
        infoAboutUser: "Info about user",
        lang: "Language:",
        login: "Login",
        name: "Name",
        score: "Balance",
        surname: "Surname",
        password: "Password",
        thirdPartyEventManagement: "Third-party events management",
        ticketDate: "Date bought",
        ticketEventName: "Event name",
        ticketPrice: "Price",
        titleName: "User account",
        topUpBalance: "Top up balance",
        updateSettings: "Update settings",
        venueManagement: "Venue management",
        enterSum: "Enter sum for adding",
        nowBalance: "Now balance",
        topUp: "Top up",
        updateUserSettings: "Update user settings",
        areYouSure: "Are you sure?",
        success: "Success!",
        fail: "Fail...",
        successReload: "Success! You need relogin after update user-settings.",
    },
    ru: {
        age: "Возраст",
        boughtTickets: "Купленные билеты",
        email: "Email",
        eventManagement: "Управление событиями",
        exit: "Выход",
        infoAboutUser: "Информация о пользователе",
        lang: "Язык:",
        login: "Логин",
        name: "Имя",
        score: "Баланс",
        surname: "Фамилия",
        password: "Password",
        thirdPartyEventManagement: "Управление сторонними событиями",
        ticketDate: "Дата покупки",
        ticketEventName: "Название события",
        ticketPrice: "Цена",
        titleName: "Личный кабинет",
        topUpBalance: "Пополнить баланс",
        updateSettings: "Изменить настройки",
        venueManagement: "Управление местами проведения",
        enterSum: "Введите сумму для добавления",
        nowBalance: "Текущий баланс",
        topUp: "Пополнить",
        updateUserSettings: "Изменение пользовательских настроек",
        areYouSure: "Вы уверены?",
        success: "Успешно!",
        fail: "Неудачно...",
        successReload: "Успешно! Вам нужно войти в аккаунт еще раз после изменения пользовательских настроек.",
    },
    be: {
        age: "Ўзрост",
        boughtTickets: "Набытыя квіткі",
        email: "Email",
        eventManagement: "Кіраванне падзеямі",
        exit: "Выхад",
        infoAboutUser: "Інфармацыя пра карыстальніка",
        lang: "Мова:",
        login: "Лагін",
        name: "Імя",
        score: "Баланс",
        surname: "Прозвішча",
        password: "Пароль",
        thirdPartyEventManagement: "Кіраванне іншымі падзеямі",
        ticketDate:	"Дата пакупкі",
        ticketEventName: "Назва падзеі",
        ticketPrice: "Цана",
        titleName: "Асабісты кабінет",
        topUpBalance: "Папоўніць баланс",
        updateSettings:	"Змяніць налады",
        venueManagement: "Кіраванне месцамі правядзення",
        enterSum: "Увядзіце суму для папаўнення",
        nowBalance: "Цяперашні баланс",
        topUp: "Папоўніць",
        updateUserSettings: "Змена налад карыстальніка",
        areYouSure: "Вы ўпэўнены?",
        success: "Паспяхова!",
        fail: "Няўдала...",
        successReload: "Паспяхова! Вам трэба ўвайсці ў рахунак яшчэ раз пасля змены карыстацкіх налад.",
    }
}
export default userData;