CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(30) NOT NULL,
	Surname NVARCHAR(40) NOT NULL,
	Age INT,
	Language NVARCHAR(5) DEFAULT 'En',
	UTC DATETIMEOFFSET,
	Email NVARCHAR(40),
	Password NVARCHAR(60) NOT NULL,
	Login NVARCHAR(60),
	Score FLOAT DEFAULT 0,
); 